name: Run Fantasy Football Model Pipeline

on:
  workflow_dispatch:
    inputs:
      league_size:
        description: 'Number of teams in the league'
        required: false
        default: '14'
  schedule:
    - cron: '0 12 * * 1' # Runs every Monday at 12:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pipeline
        env:
          SPORTSBOOKAPI_KEY: ${{ secrets.SPORTSBOOKAPI_KEY }}
        run: |
          python src/main.py ${{ github.event.inputs.league_size || '14' }}

      - name: Upload Excel output
        uses: actions/upload-artifact@v4
        with:
          name: fantasy-big-board
          path: fantasy_big_board.xlsx 