name: Run Fantasy Football Model Pipeline

on:
  workflow_dispatch:
    inputs:
      league_size:
        description: 'Number of teams in the league'
        required: false
        default: '14'
  schedule:
    - cron: '0 12 * 7,8 *' # Runs daily at 12:00 UTC in July and August only

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pipeline
        env:
          SPORTSBOOKAPI_KEY: ${{ secrets.SPORTSBOOKAPI_KEY }}
        run: |
          python src/main.py ${{ github.event.inputs.league_size || '14' }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%m%d%y')" >> $GITHUB_OUTPUT

      - name: Upload Excel output
        uses: actions/upload-artifact@v4
        with:
          name: fantasy-big-board-${{ steps.date.outputs.date }}
          path: fantasy_big_board_*.xlsx

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Fantasy Football Big Board - ${{ steps.date.outputs.date }}"
          to: debarun.de20@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            Hi Debarun,
            
            Your daily fantasy football big board has been generated and is attached to this email.
            
            Date: ${{ steps.date.outputs.date }}
            League Size: ${{ github.event.inputs.league_size || '14' }} teams
            
            The Excel file contains:
            - ADP Comparison with value recommendations
            - Unified Big Board rankings
            - Position-specific rankings (QB, RB, WR, TE)
            - Draft management with conditional formatting
            
            Best regards,
            Your Fantasy Football Model
          attachments: fantasy_big_board_*.xlsx 